CREATE TABLE public.challenges (
	id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	challenge varchar NULL,
	potentialanswer1 varchar NULL,
	potentialanswer2 varchar NULL,
	potentialanswer3 varchar NULL,
	potentialanswer4 varchar NULL,
	answer varchar NULL
);

CREATE TABLE public.answered (
	id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"user" varchar NULL,
	answer varchar NULL,
	"date" date DEFAULT now() NULL,
    challenge int,
    dateassigned date,
);
